import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ProviderWrapper } from '@/redux/providerWrapper';
import { ThemeProvider } from '@/components/ThemeProvider';
import { LoadingProvider } from '@/components/LoadingProvider';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`min-h-screen bg-background antialiased ${inter.className}`}>
        <ProviderWrapper>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <LoadingProvider>
              <Navbar />
              {children}
            </LoadingProvider>
          </ThemeProvider>
        </ProviderWrapper>
      </body>
    </html>
  );
}